services:


  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      JWT_SECRET_KEY: knLRUQMiyDy7S3gsYPqoWDoWw0OM5aGE2CERTMKGT24

      POSTGRES_USER: admin
      POSTGRES_PASSWORD: amir112233
      POSTGRES_DB: edumanager
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: backend_redis
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_fastapi
    environment:
      REDIS_URL: redis://redis:6379
       
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/core
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload               

volumes:
  postgres_data:
  redis_data:


