version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: amir112233
      POSTGRES_DB: edumanager
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: backend_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    restart: always
    environment:
      REDIS_URL: redis://redis:6379
      JWT_SECRET_KEY: knLRUQMiyDy7S3gsYPqoWDoWw0OM5aGE2CERTMKGT24
     
      SQLALCHEMY_DATABASE_URL: postgresql+asyncpg://admin:amir112233@db:5432/edumanager
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: amir112233
      DB_NAME: edumanager
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/core
    command: bash -c 'celery -A app.celery_conf worker --loglevel=info'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_fastapi
    restart: always
    environment:
      REDIS_URL: redis://redis:6379
      JWT_SECRET_KEY: knLRUQMiyDy7S3gsYPqoWDoWw0OM5aGE2CERTMKGT24
      # توصیه می‌شود SQLALCHEMY_DATABASE_URL را اینجا هم قرار دهید
      SQLALCHEMY_DATABASE_URL: postgresql+asyncpg://admin:amir112233@db:5432/edumanager
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: amir112233
      DB_NAME: edumanager
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/core
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  flower:
    image: mher/flower:0.9.7
    command: ["flower", "--broker=redis//:redis:6379/3", "--port=5555"]
    ports: 
      - 5555:5555

    depends_on: 
      - redis     



volumes:
  postgres_data:
  redis_data:
