"""foregin key to user from tickets tables

Revision ID: 84d85b61019c
Revises: c5d6a2d6ca61
Create Date: 2025-10-22 08:26:14.163285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d85b61019c'
down_revision: Union[str, Sequence[str], None] = 'c5d6a2d6ca61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'created_by')
    # ### end Alembic commands ###
