"""change bootcamp status

Revision ID: c5d6a2d6ca61
Revises: b317efbc1ffd
Create Date: 2025-10-20 09:08:53.719548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5d6a2d6ca61'
down_revision: Union[str, Sequence[str], None] = 'b317efbc1ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bootcamps', 'status',
               existing_type=postgresql.ENUM('draft', 'available', 'finished', 'canceled', name='bootcampstatus'),
               type_=sa.Enum('draft', 'available', 'finished', 'canceled', name='bootcampstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bootcamps', 'status',
               existing_type=sa.Enum('draft', 'available', 'finished', 'canceled', name='bootcampstatus', native_enum=False),
               type_=postgresql.ENUM('draft', 'available', 'finished', 'canceled', name='bootcampstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
