"""fix: relationship problems fixed

Revision ID: fa6d006f9430
Revises: cc649b7d613b
Create Date: 2025-10-12 17:18:15.149730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6d006f9430'
down_revision: Union[str, Sequence[str], None] = 'cc649b7d613b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bootcamps', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bootcamps', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bootcamps', type_='foreignkey')
    op.drop_column('bootcamps', 'category_id')
    # ### end Alembic commands ###
